### ISSUE TITLE
Add FF image for Century Mall Mysteries

### ISSUE THREAD

**Issue by Chuckchang23** [mysterymanila/mysterymanila.github.io#102]
Hi Team, can we add the ff files under the img folder? @jcdelfinado @rensramos 

![vv1 1](https://cloud.githubusercontent.com/assets/10861641/9649848/0bd1dae6-522d-11e5-8143-67c573d98d35.jpg)
![vv1 2](https://cloud.githubusercontent.com/assets/10861641/9649850/0bd423b4-522d-11e5-9e2b-9dc8390f73fe.jpg)
![vv1 3](https://cloud.githubusercontent.com/assets/10861641/9649849/0bd3f196-522d-11e5-8048-bc545dc80a9c.jpg)

**Comment by rensramos** [comment]
Done sir @Chuckchang23  :)

**Comment by Chuckchang23** [comment]
Hi rens, anong folder ko sya makikita para mareferencw ko siya? Can we move it to poster folder para lahat andun?

**Comment by rensramos** [comment]
Yup ok na po.
