### ISSUE TITLE
Update Corporate Tab

### ISSUE THREAD

**Issue by Chuckchang23** [mysterymanila/mysterymanila.github.io#103]
Hi Team, 

Not sure how this issue thing works hehe

Requesting to update the corporate tab to this one. 

![capture](https://cloud.githubusercontent.com/assets/10861641/10651736/da0b9f24-7883-11e5-92ee-1aff0eddc97e.JPG)

attached are the text and image for the ff columns

***We have special corporate packages which can be customized for your specific group size and need

***We also do customized mysteries for special corporate events and media launches

***Be the killer, victim or witness!

Check out our sister company
www.murdermanila.com
for details.
![deal](https://cloud.githubusercontent.com/assets/10861641/10651603/1e368c00-7883-11e5-8b54-017d6b1db777.png)
![gear](https://cloud.githubusercontent.com/assets/10861641/10651601/1e30344a-7883-11e5-879b-5b5e28828e3b.png)
![mainlogo](https://cloud.githubusercontent.com/assets/10861641/10651602/1e33b174-7883-11e5-9544-8a1a54c379f9.gif)

for the murder manila logo, update ko na lang file. I'll ask the logo from my partner lang

**Comment by bryanchug** [comment]
@rensramos, please tell Gerardo to accept invitation to mysterymanila team.
