### ISSUE TITLE
Add poster for Debby's Doll

### ISSUE THREAD

**Issue by Chuckchang23** [mysterymanila/mysterymanila.github.io#105]
Hi @rensramos 

Please add this image for poster of Debby;s Doll.

Kindly name the file as dd.jpg for it to reflect on the rooms.yml

@bryanchug Try niyo siya asap!!!

![dd](https://cloud.githubusercontent.com/assets/10861641/11821094/cebd5f3c-a3a2-11e5-8130-27387e955cda.jpg)

**Comment by rensramos** [comment]
Good day @Chuckchang23 done na po :)
