### ISSUE TITLE
Can we use futura as the generic font? 

### ISSUE THREAD

**Issue by rensramos** [mysterymanila/mysterymanila.github.io#22]
We're ok with the font used in "the first live..." said by Mysterymanila Owner

**Comment by jericodelfinado** [comment]
@mysterymanila/owners should decide this

**Comment by bryanchug** [comment]
Please assign this to Senday.

**Comment by rensramos** [comment]
Solved on issue #64

**Comment by jericodelfinado** [comment]
typekit still forbidden for mysterymanila.github.io
