### ISSUE TITLE
Upload other videos

### ISSUE THREAD

**Issue by bryanchug** [mysterymanila/mysterymanila.github.io#5]
- Rebecca's Room
- Reverse Reality
- Sinister Sensorium

**Comment by bryanchug** [comment]
Updated Video URLs

URL prefix: (This is a CDN, will introduce you guys to concept of CDN.)
http://d3pfdit6z4xogx.cloudfront.net/videos/

| Room | Filename |
| --- | --- |
| Sinister Sensorium | MM_Sinister.mp4 |
| Rebecca's Room | MM_Rebecca.mp4 |
| World of Wizardry | MM_WorldOfWizardry.mp4 |
| The Ticking Time Bomb | MM_TimeBomb.mp4 |
| Buried Bodies | MM_BuriedBodies.mp4 |
| Reverse Reality | MM_ReversedReality.mp4 |

Sample:
http://d3pfdit6z4xogx.cloudfront.net/videos/MM_Sinister.mp4

FINAL

**Comment by bryanchug** [comment]
@rensramos use these.

**Comment by jericodelfinado** [comment]
Done.
