### ISSUE TITLE
fix navbar title 

### ISSUE THREAD

**Issue by rensramos** [mysterymanila/mysterymanila.github.io#59]
On some load instances, 'Mystery Manila' breaks to a new line on navbar
Add navbar collapse breakpoint on 900px viewport

**Comment by jericodelfinado** [comment]
@rensramos don't forget to describe the issues so we know what we're dealing with.

**Comment by jericodelfinado** [comment]
On some load instances, 'Mystery Manila' breaks to a new line on navbar

**Comment by rensramos** [comment]
Done adding navbar break point for 900px,
I think the issue of breaking new lines was already solved on last pull request #64 .
I tried it many times and i won't break.

**Comment by rensramos** [comment]
Done
